function checkResult(a,b) {
    return new Promise ((resolve,reject) => {
        setTimeout(() => {
            if (a + b == 8){
                resolve ("ok")
            } else {
                reject ("Ko")
            }
        },5000)
    })
}
 

const result = checkResult(5,2).then ((data) => {
    console.log(data)
 }).catch((error) => {
    console.log(error)
 })
       
